# Elastic search mapping definition for the Molecule entity
from glados.es.ws2es.es_util import DefaultMappings

# Shards size - can be overridden from the default calculated value here
# shards = 3,
replicas = 1

analysis = DefaultMappings.COMMON_ANALYSIS

mappings = \
    {
        'properties': 
        {
            'biocomponents': 
            {
                'properties': 
                {
                    'component_id': 'NUMERIC',
                    # EXAMPLES:
                    # '6507' , '17008' , '8377' , '6545' , '6563' , '8650' , '6348' , '6318' , '6318' , '6565'
                    'component_type': 'TEXT',
                    # EXAMPLES:
                    # 'PROTEIN' , 'RNA' , 'PROTEIN' , 'PROTEIN' , 'PROTEIN' , 'PROTEIN' , 'PROTEIN' , 'PROTEIN' , 'PROTE
                    # IN' , 'PROTEIN'
                    'description': 'TEXT',
                    # EXAMPLES:
                    # 'Orticumab heavy chain' , 'Eteplirsen oligonucleotide' , 'Asfotase alfa fusion protein' , 'Conberc
                    # ept fusion protein' , 'Clazakizumab heavy chain' , 'Thrombomodulin alfa' , 'Bezlotoxumab heavy cha
                    # in' , 'Vorsetuzumab heavy chain' , 'Vorsetuzumab heavy chain' , 'Sarilumab heavy chain'
                    'organism': 'TEXT',
                    # EXAMPLES:
                    # 'Homo sapiens' , 'Homo sapiens' , 'Homo sapiens' , 'Homo sapiens' , 'Homo sapiens' , 'Homo sapiens
                    # ' , 'Homo sapiens' , 'Mus musculus' , 'Homo sapiens' , 'Homo sapiens'
                    'sequence': 'TEXT',
                    # EXAMPLES:
                    # 'EVQLLESGGGLVQPGGSLRLSCAASGFTFSNAWMSWVRQAPGKGLEWVSSISVGGHRTYYADSVKGRSTISRDNSKNTLYLQMNSLRAEDTAVYYCA
                    # RIRVGPSGGAFDYWGQGTLVTVSSASTKGPSVFPLAPSSKSTSGGTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSS
                    # SLGTQTYICNVNHKPSNTKVDKKVEPKSCDKTHTCPPCPAPELLGGPSVFLFPPKPKDTLMISRTPEVTCVVVDVSHEDPEVKFNWYVDGVEVHNAKT
                    # KPREEQYNSTYRVVSVLTVLHQDWLNGKEYKCKVSNKALPAPIEKTISKAKGQPREPQVYTLPPSRDELTKNQVSLTCLVKGFYPSDIAVEWESNGQP
                    # ENNYKTTPPVLDSDGSFFLYSKLTVDKSRWQQGNVFSCSVMHEALHNHYTQKSLSLSPGK' , 'CTCCAACATCAAGGAAGATGGCATTTCTAG' ,
                    #  'LVPEKEKDPKYWRDQAQETLKYALELQKLNTNVAKNVIMFLGDGMGVSTVTAARILKGQLHHNPGEETRLEMDKFPFVALSKTYNTNAQVPDSAGT
                    # ATAYLCGVKANEGTVGVSAATERSRCNTTQGNEVTSILRWAKDAGKSVGIVTTTRVNHATPSAAYAHSADRDWYSDNEMPPEALSQGCKDIAYQLMHN
                    # IRDIDVIMGGGRKYMYPKNKTDVEYESDEKARGTRLDGLDLVDTWKSFKPRYKHSHFIWNRTELLTLDPHNVDYLLGLFEPGDMQYELNRNNVTDPSL
                    # SEMVVVAIQILRKNPKGFFLLVEGGRIDHGHHEGKAKQALHEAVEMDRAIGQAGSLTSSEDTLTVVTADHSHVFTFGGYTPRGNSIFGLAPMLSDTDK
                    # KPFTAILYGNGPGYKVVGGERENVSMVDYAHNNYQAQSAVPLRHETHGGEDVAVFSKGPMAHLLHGVHEQNYVPHVMAYAACIGANLGHCAPASSLKD
                    # KTHTCPPCPAPELLGGPSVFLFPPKPKDTLMISRTPEVTCVVVDVSHEDPEVKFNWYVDGVEVHNAKTKPREEQYNSTYRVVSVLTVLHQDWLNGKEY
                    # KCKVSNKALPAPIEKTISKAKGQPREPQVYTLPPSREEMTKNQVSLTCLVKGFYPSDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSKLTVDKSRW
                    # QQGNVFSCSVMHEALHNHYTQKSLSLSPGKDIDDDDDDDDDD' , 'GRPFVEMYSEIPEIIHMTEGRELVIPCRVTSPNITVTLKKFPLDTLIPDGK
                    # RIIWDSRKGFIISNATYKEIGLLTCEATVNGHLYKTNYLTHRQTNTIIDVVLSPSHGIELSVGEKLVLNCTARTELNVGIDFNWEYPSSKHQHKKLVN
                    # RDLKTQSGSEMKKFLSTLTIDGVTRSDQGLYTCAASSGLMTKKNSTFVRVHEKPFVAFGSGMESLVEATVGERVRIPAKYLGYPPPEIKWYKNGIPLE
                    # SNHTIKAGHVLTIMEVSERDTGNYTVILTNPISKEKQSHVVSLVVYVPPGPGDKTHTCPLCPAPELLGGPSVFLFPPKPKDTLMISRTPEVTCVVVDV
                    # SHEDPEVKFNWYVDGVEVHNAKTKPREEQYNSTYRVVSVLTVLHQDWLNGKEYKCKVSNKALPAPIEKTISKAKGQPREPQVYTLPPSRDELTKNQVS
                    # LTCLVKGFYPSDIAVEWESNGQPENNYKATPPVLDSDGSFFLYSKLTVDKSRWQQGNVFSCSVMHEALHNHYTQKSLSLSPGK' , 'EVQLVESGGG
                    # LVQPGGSLRLSCAASGFSLSNYYVTWVRQAPGKGLEWVGIIYGSDETAYATSAIGRFTISRDNSKNTLYLQMNSLRAEDTAVYYCARDDSSDWDAKFN
                    # LWGQGTLVTVSSASTKGPSVFPLAPSSKSTSGGTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTQTYICNVN
                    # HKPSNTKVDKRVEPKSCDKTHTCPPCPAPELLGGPSVFLFPPKPKDTLMISRTPEVTCVVVDVSHEDPEVKFNWYVDGVEVHNAKTKPREEQYASTYR
                    # VVSVLTVLHQDWLNGKEYKCKVSNKALPAPIEKTISKAKGQPREPQVYTLPPSREEMTKNQVSLTCLVKGFYPSDIAVEWESNGQPENNYKTTPPVLD
                    # SDGSFFLYSKLTVDKSRWQQGNVFSCSVMHEALHNHYTQKSLSLSPGK' , 'APAEPQPGGSQCVEHDCFALYPGPATFLNASQICDGLRGHLMTVR
                    # SSVAADVISLLLNGDGGVGRRRLWIGLQLPPGCGDPKRLGPLRGFQWVTGDNNTSYSRWARLDLNGAPLCGPLCVAVSAAEATVPSEPIWEEQQCEVK
                    # ADGFLCEFHFPATCRPLAVEPGAAAAAVSITYGTPFAARGADFQALPVGSSAAVAPLGLQLMCTAPPGAVQGHWAREAPGAWDCSVENGGCEHACNAI
                    # PGAPRCQCPAGAALQADGRSCTASATQSCNDLCEHFCVPNPDQPGSYSCMCETGYRLAADQHRCEDVDDCILEPSPCPQRCVNTQGGFECHCYPNYDL
                    # VDGECVEPVDPCFRANCEYQCQPLNQTSYLCVCAEGFAPIPHEPHRCQMFCNQTACPADCDPNTQASCECPEGYILDDGFICTDIDECENGGFCSGVC
                    # HNLPGTFECICGPDSALVRHIGTDCDSGKVDGGDSGSGEPPPSPTPGSTLTPPAVGLVHSG' , 'EVQLVQSGAEVKKSGESLKISCKGSGYSFTSY
                    # WIGWVRQMPGKGLEWMGIFYPGDSSTRYSPSFQGQVTISADKSVNTAYLQWSSLKASDTAMYYCARRRNWGNAFDIWGQGTMVTVSSASTKGPSVFPL
                    # APSSKSTSGGTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKRVEPKSCDKTHTC
                    # PPCPAPELLGGPSVFLFPPKPKDTLMISRTPEVTCVVVDVSHEDPEVKFNWYVDGVEVHNAKTKPREEQYNSTYRVVSVLTVLHQDWLNGKEYKCKVS
                    # NKALPAPIEKTISKAKGQPREPQVYTLPPSREEMTKNQVSLTCLVKGFYPSDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSKLTVDKSRWQQGNV
                    # FSCSVMHEALHNHYTQKSLSLSPGK' , 'QVQLVQSGAEVKKPGASVKVSCKASGYTFTNYGMNWVRQAPGQGLKWMGWINTYTGEPTYADAFKGRV
                    # TMTRDTSISTAYMELSRLRSDDTAVYYCARDYGDYGMDYWGQGTTVTVSSASTKGPSVFPLAPSSKSTSGGTAALGCLVKDYFPEPVTVSWNSGALTS
                    # GVHTFPAVLQSSGLYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKKVEPKSCDKTHTCPPCPAPELLGGPSVFLFPPKPKDTLMISRTPEVTCVV
                    # VDVSHEDPEVKFNWYVDGVEVHNAKTKPREEQYNSTYRVVSVLTVLHQDWLNGKEYKCKVSNKALPAPIEKTISKAKGQPREPQVYTLPPSRDELTKN
                    # QVSLTCLVKGFYPSDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSKLTVDKSRWQQGNVFSCSVMHEALHNHYTQKSLSLSPGK' , 'QVQLVQS
                    # GAEVKKPGASVKVSCKASGYTFTNYGMNWVRQAPGQGLKWMGWINTYTGEPTYADAFKGRVTMTRDTSISTAYMELSRLRSDDTAVYYCARDYGDYGM
                    # DYWGQGTTVTVSSASTKGPSVFPLAPSSKSTSGGTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTQTYICNV
                    # NHKPSNTKVDKKVEPKSCDKTHTCPPCPAPELLGGPSVFLFPPKPKDTLMISRTPEVTCVVVDVSHEDPEVKFNWYVDGVEVHNAKTKPREEQYNSTY
                    # RVVSVLTVLHQDWLNGKEYKCKVSNKALPAPIEKTISKAKGQPREPQVYTLPPSRDELTKNQVSLTCLVKGFYPSDIAVEWESNGQPENNYKTTPPVL
                    # DSDGSFFLYSKLTVDKSRWQQGNVFSCSVMHEALHNHYTQKSLSLSPGK' , 'EVQLVESGGGLVQPGRSLRLSCAASRFTFDDYAMHWVRQAPGKG
                    # LEWVSGISWNSGRIGYADSVKGRFTISRDNAENSLFLQMNGLRAEDTALYYCAKGRDSFDIWGQGTMVTVSSASTKGPSVFPLAPSSKSTSGGTAALG
                    # CLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKKVEPKSCDKTHTCPPCPAPELLGGPSVF
                    # LFPPKPKDTLMISRTPEVTCVVVDVSHEDPEVKFNWYVDGVEVHNAKTKPREEQYNSTYRVVSVLTVLHQDWLNGKEYKCKVSNKALPAPIEKTISKA
                    # KGQPREPQVYTLPPSRDELTKNQVSLTCLVKGFYPSDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSKLTVDKSRWQQGNVFSCSVMHEALHNHYT
                    # QKSLSLSPGK'
                    'tax_id': 'NUMERIC',
                    # EXAMPLES:
                    # '9606' , '9606' , '9606' , '9606' , '9606' , '9606' , '9606' , '10090' , '9606' , '9606'
                }
            },
            'description': 'TEXT',
            # EXAMPLES:
            # 'CDP-7657 (mab)' , 'PF-03475952 (mab)' , 'AHN-12 (mab)' , 'BB-10901 (mab)' , 'CDP-850 (humanized mab)' , '
            # MDX-1411 (mab)' , 'E2.3 (mab)' , 'IGN-311 (mab)' , 'ImmuRAIT-LL2 (mouse mab)' , 'MCS-110 (mab)'
            'helm_notation': 'TEXT',
            # EXAMPLES:
            # 'PEPTIDE1{[X1969].[dC].H.[dW].K.V.C.[Nal].[am]}$PEPTIDE1,PEPTIDE1,7:R3-2:R3$$$' , 'PEPTIDE1{[X1969].[dC].H
            # .[dW].K.V.C.[X1969].[am]}$PEPTIDE1,PEPTIDE1,7:R3-2:R3$$$' , 'PEPTIDE1{[Nal].[dC].[3-Pal].[dW].K.V.C.Y.[am]
            # }$PEPTIDE1,PEPTIDE1,7:R3-2:R3$$$' , 'PEPTIDE1{[Glp].L.Y.E.N.K.P.[dR].R.P.Y.I.L}$$$$' , 'PEPTIDE1{R.P.K.[dP
            # ].Q.[dQ].[dF].[dF].G.L.M.[am]}$$$$' , 'PEPTIDE1{A.A.R.E.R.R.R.K.K.R.[Sar]}$$$$' , 'PEPTIDE1{[X1640].[Tic]}
            # |PEPTIDE2{[X1640].[Tic].[dK].[am]}$PEPTIDE2,PEPTIDE1,3:R3-2:R2$$$' , 'PEPTIDE1{[Glp].L.Y.E.N.K.P.R.R.P.Y.[
            # dI].L}$$$$' , 'PEPTIDE1{R.P.K.[dP].Q.[dQ].[dF].F.G.L.M.[am]}$$$$' , 'PEPTIDE1{D.C.L.G.I.M.R.K.C.I.P.D.N.D.
            # K.C.C.R.P.N.L.V.C.S.R.T.H.K.W.C.K.Y.V.F.[am]}$PEPTIDE1,PEPTIDE1,23:R3-9:R3|PEPTIDE1,PEPTIDE1,17:R3-2:R3|PE
            # PTIDE1,PEPTIDE1,30:R3-16:R3$$$'
            'molecule_chembl_id': 'TEXT',
            # EXAMPLES:
            # 'CHEMBL3349667' , 'CHEMBL2109478' , 'CHEMBL3349668' , 'CHEMBL2109479' , 'CHEMBL3349669' , 'CHEMBL2109480' 
            # , 'CHEMBL3278505' , 'CHEMBL384582' , 'CHEMBL498977' , 'CHEMBL2035778'
        }
    }
