# Elastic search mapping definition for the Molecule entity
from glados.es.ws2es.es_util import DefaultMappings

# Shards size - can be overridden from the default calculated value here
# shards = 3,
replicas = 1

analysis = DefaultMappings.COMMON_ANALYSIS

mappings = \
    {
        'properties': 
        {
            'accession': 'TEXT',
            # EXAMPLES:
            # 'P50993' , 'Q8WUI4' , 'Q9HCR9' , 'P70579' , 'P27824' , 'P79266' , 'P43005' , 'P19099' , 'P30306' , 'P06211
            # '
            'component_id': 'NUMERIC',
            # EXAMPLES:
            # '1051' , '1052' , '1053' , '1054' , '1055' , '1056' , '1057' , '1058' , '1059' , '1060'
            'component_type': 'TEXT',
            # EXAMPLES:
            # 'PROTEIN' , 'PROTEIN' , 'PROTEIN' , 'PROTEIN' , 'PROTEIN' , 'PROTEIN' , 'PROTEIN' , 'PROTEIN' , 'PROTEIN' 
            # , 'PROTEIN'
            'description': 'TEXT',
            # EXAMPLES:
            # 'Sodium/potassium-transporting ATPase subunit alpha-2' , 'Histone deacetylase 7' , 'Dual 3',5'-cyclic-AMP 
            # and -GMP phosphodiesterase 11A' , 'Metabotropic glutamate receptor 8' , 'Calnexin' , 'Gastrin/cholecystoki
            # nin type B receptor' , 'Excitatory amino acid transporter 3' , 'Cytochrome P450 11B2, mitochondrial' , 'M-
            # phase inducer phosphatase 2' , 'Estrogen receptor'
            'go_slims': 
            {
                'properties': 
                {
                    'go_id': 'TEXT',
                    # EXAMPLES:
                    # 'GO:0000166' , 'GO:0003674' , 'GO:0000166' , 'GO:0003674' , 'GO:0002376' , 'GO:0004930' , 'GO:0003
                    # 013' , 'GO:0003674' , 'GO:0005575' , 'GO:0003674'
                }
            },
            'organism': 'TEXT',
            # EXAMPLES:
            # 'Homo sapiens' , 'Homo sapiens' , 'Homo sapiens' , 'Rattus norvegicus' , 'Homo sapiens' , 'Bos taurus' , '
            # Homo sapiens' , 'Homo sapiens' , 'Mus musculus' , 'Rattus norvegicus'
            'protein_classifications': 
            {
                'properties': 
                {
                    'protein_classification_id': 'NUMERIC',
                    # EXAMPLES:
                    # '494' , '842' , '124' , '446' , '8' , '540' , '690' , '225' , '279' , '370'
                }
            },
            'sequence': 'TEXT',
            # EXAMPLES:
            # 'MGRGAGREYSPAATTAENGGGKKKQKEKELDELKKEVAMDDHKLSLDELGRKYQVDLSKGLTNQRAQDVLARDGPNALTPPPTTPEWVKFCRQLFGGFSILLWIG
            # AILCFLAYGIQAAMEDEPSNDNLYLGVVLAAVVIVTGCFSYYQEAKSSKIMDSFKNMVPQQALVIREGEKMQINAEEVVVGDLVEVKGGDRVPADLRIISSHGCKV
            # DNSSLTGESEPQTRSPEFTHENPLETRNICFFSTNCVEGTARGIVIATGDRTVMGRIATLASGLEVGRTPIAMEIEHFIQLITGVAVFLGVSFFVLSLILGYSWLE
            # AVIFLIGIIVANVPEGLLATVTVCLTLTAKRMARKNCLVKNLEAVETLGSTSTICSDKTGTLTQNRMTVAHMWFDNQIHEADTTEDQSGATFDKRSPTWTALSRIA
            # GLCNRAVFKAGQENISVSKRDTAGDASESALLKCIELSCGSVRKMRDRNPKVAEIPFNSTNKYQLSIHEREDSPQSHVLVMKGAPERILDRCSTILVQGKEIPLDK
            # EMQDAFQNAYMELGGLGERVLGFCQLNLPSGKFPRGFKFDTDELNFPTEKLCFVGLMSMIDPPRAAVPDAVGKCRSAGIKVIMVTGDHPITAKAIAKGVGIISEGN
            # ETVEDIAARLNIPMSQVNPREAKACVVHGSDLKDMTSEQLDEILKNHTEIVFARTSPQQKLIIVEGCQRQGAIVAVTGDGVNDSPALKKADIGIAMGISGSDVSKQ
            # AADMILLDDNFASIVTGVEEGRLIFDNLKKSIAYTLTSNIPEITPFLLFIIANIPLPLGTVTILCIDLGTDMVPAISLAYEAAESDIMKRQPRNSQTDKLVNERLI
            # SMAYGQIGMIQALGGFFTYFVILAENGFLPSRLLGIRLDWDDRTMNDLEDSYGQEWTYEQRKVVEFTCHTAFFASIVVVQWADLIICKTRRNSVFQQGMKNKILIF
            # GLLEETALAAFLSYCPGMGVALRMYPLKVTWWFCAFPYSLLIFIYDEVRKLILRRYPGGWVEKETYY' , 'MDLRVGQRPPVEPPPEPTLLALQRPQRLHHHLFL
            # AGLQQQRSVEPMRLSMDTPMPELQVGPQEQELRQLLHKDKSKRSAVASSVVKQKLAEVILKKQQAALERTVHPNSPGIPYRTLEPLETEGATRSMLSSFLPPVPSL
            # PSDPPEHFPLRKTVSEPNLKLRYKPKKSLERRKNPLLRKESAPPSLRRRPAETLGDSSPSSSSTPASGCSSPNDSEHGPNPILGSEALLGQRLRLQETSVAPFALP
            # TVSLLPAITLGLPAPARADSDRRTHPTLGPRGPILGSPHTPLFLPHGLEPEAGGTLPSRLQPILLLDPSGSHAPLLTVPGLGPLPFHFAQSLMTTERLSGSGLHWP
            # LSRTRSEPLPPSATAPPPPGPMQPRLEQLKTHVQVIKRSAKPSEKPRLRQIPSAEDLETDGGGPGQVVDDGLEHRELGHGQPEARGPAPLQQHPQVLLWEQQRLAG
            # RLPRGSTGDTVLLPLAQGGHRPLSRAQSSPAAPASLSAPEPASQARVLSSSETPARTLPFTTGLIYDSVMLKHQCSCGDNSRHPEHAGRIQSIWSRLQERGLRSQC
            # ECLRGRKASLEELQSVHSERHVLLYGTNPLSRLKLDNGKLAGLLAQRMFVMLPCGGVGVDTDTIWNELHSSNAARWAAGSVTDLAFKVASRELKNGFAVVRPPGHH
            # ADHSTAMGFCFFNSVAIACRQLQQQSKASKILIVDWDVHHGNGTQQTFYQDPSVLYISLHRHDDGNFFPGSGAVDEVGAGSGEGFNVNVAWAGGLDPPMGDPEYLA
            # AFRIVVMPIAREFSPDLVLVSAGFDAAEGHPAPLGGYHVSAKCFGYMTQQLMNLAGGAVVLALEGGHDLTAICDASEACVAALLGNRVDPLSEEGWKQKPNLNAIR
            # SLEAVIRVHSKYWGCMQRLASCPDSWVPRVPGADKEEVEAVTALASLSVGILAEDRPSEQLVEEEEPMNL' , 'MAASRLDFGEVETFLDRHPELFEDYLMRKGK
            # QEMVEKWLQRHSQGQGALGPRPSLAGTSSLAHSTCRGGSSVGGGTGPNGSAHSQPLPGGGDCGGVPLSPSWAGGSRGDGNLQRRASQKELRKSFARSKAIHVNRTY
            # DEQVTSRAQEPLSSVRRRALLRKASSLPPTTAHILSALLESRVNLPRYPPTAIDYKCHLKKHNERQFFLELVKDISNDLDLTSLSYKILIFVCLMVDADRCSLFLV
            # EGAAAGKKTLVSKFFDVHAGTPLLPCSSTENSNEVQVPWGKGIIGYVGEHGETVNIPDAYQDRRFNDEIDKLTGYKTKSLLCMPIRSSDGEIIGVAQAINKIPEGA
            # PFTEDDEKVMQMYLPFCGIAISNAQLFAASRKEYERSRALLEVVNDLFEEQTDLEKIVKKIMHRAQTLLKCERCSVLLLEDIESPVVKFTKSFELMSPKCSADAEN
            # SFKESMEKSSYSDWLINNSIAELVASTGLPVNISDAYQDPRFDAEADQISGFHIRSVLCVPIWNSNHQIIGVAQVLNRLDGKPFDDADQRLFEAFVIFCGLGINNT
            # IMYDQVKKSWAKQSVALDVLSYHATCSKAEVDKFKAANIPLVSELAIDDIHFDDFSLDVDAMITAALRMFMELGMVQKFKIDYETLCRWLLTVRKNYRMVLYHNWR
            # HAFNVCQLMFAMLTTAGFQDILTEVEILAVIVGCLCHDLDHRGTNNAFQAKSGSALAQLYGTSATLEHHHFNHAVMILQSEGHNIFANLSSKEYSDLMQLLKQSIL
            # ATDLTLYFERRTEFFELVSKGEYDWNIKNHRDIFRSMLMTACDLGAVTKPWEISRQVAELVTSEFFEQGDRERLELKLTPSAIFDRNRKDELPRLQLEWIDSICMP
            # LYQALVKVNVKLKPMLDSVATNRSKWEELHQKRLLASTASSSPASVMVAKEDRN' , 'MVCEGKRLASCPCFFLLTAKFYWILTMMQRTHSQEYAHSIRVDGDII
            # LGGLFPVHAKGERGVPCGELKKEKGIHRLEAMLYAIDQINKDPDLLSNITLGVRILDTCSRDTYALEQSLTFVQALIEKDASDVKCANGDPPIFTKPDKISGVIGA
            # AASSVSIMVANILRLFKIPQISYASTAPELSDNTRYDFFSRVVPPDSYQAQAMVDIVTALGWNYVSTLASEGNYGESGVEAFTQISREIGGVCIAQSQKIPREPRP
            # GEFEKIIKRLLETPNARAVIMFANEDDIRRILEAAKKLNQSGHFLWIGSDSWGSKIAPVYQQEEIAEGAVTILPKRASIDGFDRYFRSRTLANNRRNVWFAEFWEE
            # NFGCKLGSHGKRNSHIKKCTGLERIARDSSYEQEGKVQFVIDAVYSMAYALHNMHKERCPGYIGLCPRMVTIDGKELLGYIRAVNFNGSAGTPVTFNENGDAPGRY
            # DIFQYQINNKSTEYKIIGHWTNQLHLKVEDMQWANREHTHPASVCSLPCKPGERKKTVKGVPCCWHCERCEGYNYQVDELSCELCPLDQRPNINRTGCQRIPIIKL
            # EWHSPWAVVPVFIAILGIIATTFVIVTFVRYNDTPIVRASGRELSYVLLTGIFLCYSITFLMIAAPDTIICSFRRIFLGLGMCFSYAALLTKTNRIHRIFEQGKKS
            # VTAPKFISPASQLVITFSLISVQLLGVFVWFVVDPPHTIIDYGEQRTLDPENARGVLKCDISDLSLICSLGYSILLMVTCTVYAIKTRGVPETFNEAKPIGFTMYT
            # TCIIWLAFIPIFFGTAQSAEKMYIQTTTLTVSMSLSASVSLGMLYMPKVYIIIFHPEQNVQKRKRSFKAVVTAATMQSKLIQKGNDRPNGEVKSELCESLETNTSS
            # TKTTYISYSNHSI' , 'MEGKWLLCMLLVLGTAIVEAHDGHDDDVIDIEDDLDDVIEEVEDSKPDTTAPPSSPKVTYKAPVPTGEVYFADSFDRGTLSGWILSKA
            # KKDDTDDEIAKYDGKWEVEEMKESKLPGDKGLVLMSRAKHHAISAKLNKPFLFDTKPLIVQYEVNFQNGIECGGAYVKLLSKTPELNLDQFHDKTPYTIMFGPDKC
            # GEDYKLHFIFRHKNPKTGIYEEKHAKRPDADLKTYFTDKKTHLYTLILNPDNSFEILVDQSVVNSGNLLNDMTPPVNPSREIEDPEDRKPEDWDERPKIPDPEAVK
            # PDDWDEDAPAKIPDEEATKPEGWLDDEPEYVPDPDAEKPEDWDEDMDGEWEAPQIANPRCESAPGCGVWQRPVIDNPNYKGKWKPPMIDNPSYQGIWKPRKIPNPD
            # FFEDLEPFRMTPFSAIGLELWSMTSDIFFDNFIICADRRIVDDWANDGWGLKKAADGAAEPGVVGQMIEAAEERPWLWVVYILTVALPVFLVILFCCSGKKQTSGM
            # EYKKTDAPQPDVKEEEEEKEEEKDKGDEEEEGEEKLEEKQKSDAEEDGGTVSQEEEDRKPKAEEDEILNRSPRNRKPRRE' , 'MELLKPNRSVLGSGPGPGASL
            # CRSGGPLLNGSGTGNLSCEPPRIRGAGTRELELAIRVTLYAVIFLMSVGGNVLIIVVLGLSRRLRTVTNAFLLSLAVSDLLLAVACMPFTLLPNLMGTFIFGTVVC
            # KAVSYFMGVSVSVSTLSLVAIALERYSAICRPLQARVWQTRSHAARVIVATWMLSGLLMVPYPVYTAVQPAGPRVLQCMHRWPSARVRQTWSVLLLLLLFFVPGVV
            # MAVAYGLISRELYLGLRFDGDSDSESQSRVGSQGGLPGGTGQGPAQANGRCRSETRLAGEDGDGCYVQLPRSRPALEMSALTAPTPGPGSGTRPAQAKLLAKKRVV
            # RMLLVIVVLFFLCWLPVYSANTWRAFDGPGAHRALSGAPISFIHLLTYASACVNPLVYCFMHRRFRQACLDTCTRCCPRPPRARPRPLPDEDPPTPSIASLSRLSY
            # TTISTLGPG' , 'MGKPARKGCEWKRFLKNNWVLLSTVAAVVLGITTGVLVREHSNLSTLEKFYFAFPGEILMRMLKLIILPLIISSMITGVAALDSNVSGKIGL
            # RAVVYYFCTTLIAVILGIVLVVSIKPGVTQKVGEIARTGSTPEVSTVDAMLDLIRNMFPENLVQACFQQYKTKREEVKPPSDPEMNMTEESFTAVMTTAISKNKTK
            # EYKIVGMYSDGINVLGLIVFCLVFGLVIGKMGEKGQILVDFFNALSDATMKIVQIIMCYMPLGILFLIAGKIIEVEDWEIFRKLGLYMATVLTGLAIHSIVILPLI
            # YFIVVRKNPFRFAMGMAQALLTALMISSSSATLPVTFRCAEENNQVDKRITRFVLPVGATINMDGTALYEAVAAVFIAQLNDLDLGIGQIITISITATSASIGAAG
            # VPQAGLVTMVIVLSAVGLPAEDVTLIIAVDWLLDRFRTMVNVLGDAFGTGIVEKLSKKELEQMDVSSEVNIVNPFALESTILDNEDSDTKKSYVNGGFAVDKSDTI
            # SFTQTSQF' , 'MALRAKAEVCVAAPWLSLQRARALGTRAARAPRTVLPFEAMPQHPGNRWLRLLQIWREQGYEHLHLEMHQTFQELGPIFRYNLGGPRMVCVML
            # PEDVEKLQQVDSLHPCRMILEPWVAYRQHRGHKCGVFLLNGPEWRFNRLRLNPDVLSPKAVQRFLPMVDAVARDFSQALKKKVLQNARGSLTLDVQPSIFHYTIEA
            # SNLALFGERLGLVGHSPSSASLNFLHALEVMFKSTVQLMFMPRSLSRWISPKVWKEHFEAWDCIFQYGDNCIQKIYQELAFNRPQHYTGIVAELLLKAELSLEAIK
            # ANSMELTAGSVDTTAFPLLMTLFELARNPDVQQILRQESLAAAASISEHPQKATTELPLLRAALKETLRLYPVGLFLERVVSSDLVLQNYHIPAGTLVQVFLYSLG
            # RNAALFPRPERYNPQRWLDIRGSGRNFHHVPFGFGMRQCLGRRLAEAEMLLLLHHVLKHFLVETLTQEDIKMVYSFILRPGTSPLLTFRAIN' , 'MEVPLQKSA
            # PGSALSPARVLGGIQRPRHLSVFEFESDGFLGSPEPTASSSPVTTLTQTMHNLAGLGSEPPKAQVGSLSFQNRLADLSLSRRTSECSLSSESSESSDAGLCMDSPS
            # PVDPQMAERTFEQAIQAASRVIQNEQFTIKRFRSLPVRLLEHSPVLQSITNSRALDSWRKTEAGYRAAANSPGEDKENDGYIFKMPQELPHSSSAQALAEWVSRRQ
            # AFTQRPSSAPDLMCLTTEWKMEVEELSPVAQSSSLTPVERASEEDDGFVDILESDLKDDEKVPAGMENLISAPLVKKLDKEEEQDLIMFSKCQRLFRSPSMPCSVI
            # RPILKRLERPQDRDVPVQSKRRKSVTPLEEQQLEEPKARVFRSKSLCHEIENILDSDHRGLIGDYSKAFLLQTVDGKHQDLKYISPETMVALLTGKFSNIVEKFVI
            # VDCRYPYEYEGGHIKNAVNLPLERDAETFLLQRPIMPCSLDKRIILIFHCEFSSERGPRMCRFIRERDRAANDYPSLYYPEMYILKGGYKEFFPQHPNFCEPQDYR
            # PMNHEAFRDELRNFRLKTRSWAGERSRRELCSRLQDQ' , 'MTMTLHTKASGMALLHQIQGNELEPLNRPQLKMPMERALGEVYVDNSKPAVFNYPEGAAYEFNA
            # AAAAAAAGASAPVYGQSSITYGPGSEAAAFGANSLGAFPQLNSVSPSPLMLLHPPPHVSPFLHPHGHQVPYYLENEPSAYAVRDTGPPAFYRSNSDNRRQNGRERL
            # SSSSEKGNMIMESAKETRYCAVCNDYASGYHYGVWSCEGCKAFFKRSIQGHNDYMCPATNQCTIDKNRRKSCQACRLRKCYEVGMMKGGIRKDRRGGRMLKHKRQR
            # DDLEGRNEMGTSGDMRAANLWPSPLVIKHTKKNSPALSLTADQMVSALLDAEPPLIYSEYDPSRPFSEASMMGLLTNLADRELVHMINWAKRVPGFGDLNLHDQVH
            # LLECAWLEILMIGLVWRSMEHPGKLLFAPNLLLDRNQGKCVEGMVEIFDMLLATSSRFRMMNLQGEEFVCLKSIILLNSGVYTFLSSTLKSLEEKDHIHRVLDKIN
            # DTLIHLMAKAGLTLQQQHRRLAQLLLILSHIRHMSNKGMEHLYNMKCKNVVPLYDLLLEMLDAHRLHAPASRMGVPPEEPSQSQLTTTSSTSAHSLQTYYIPPEAE
            # GFPNTI'
            'target_component_synonyms': 
            {
                'properties': 
                {
                    'component_synonym': 'TEXT',
                    # EXAMPLES:
                    # '7.2.2.13' , '3.5.1.98' , '3.1.4.35' , 'Gprc1h' , 'Calnexin' , 'CCK2-R' , 'EAAC1' , '1.14.15.4' , 
                    # '3.1.3.48' , 'ER-alpha'
                    'syn_type': 'TEXT',
                    # EXAMPLES:
                    # 'EC_NUMBER' , 'EC_NUMBER' , 'EC_NUMBER' , 'GENE_SYMBOL_OTHER' , 'UNIPROT' , 'UNIPROT' , 'GENE_SYMB
                    # OL_OTHER' , 'EC_NUMBER' , 'EC_NUMBER' , 'UNIPROT'
                }
            },
            'target_component_xrefs': 
            {
                'properties': 
                {
                    'xref_id': 'TEXT',
                    # EXAMPLES:
                    # 'ATP1A2' , 'ENSG00000061273' , 'PDE11A' , 'GO:0005886' , 'ENSG00000127022' , 'GO:0005886' , 'SLC1A
                    # 1' , 'CYP11B2' , 'P30306' , 'GO:0000790'
                    'xref_name': 'TEXT',
                    # EXAMPLES:
                    # 'Alternating hemiplegia of childhood; Migraine, familial hemiplegic 2' , 'histone deacetylase comp
                    # lex' , 'Pigmented nodular adrenocortical disease, primary, 2' , 'plasma membrane' , 'cytoplasm' , 
                    # 'plasma membrane' , 'Schizophrenia' , 'Corticosterone methyloxidase type I deficiency; Corticoster
                    # one methyloxidase type II deficiency;  Glucocorticoid-remediable aldosteronism' , 'spindle pole' ,
                    #  'nuclear chromatin'
                    'xref_src_db': 'TEXT',
                    # EXAMPLES:
                    # 'CGD' , 'EnsemblGene' , 'CGD' , 'GoComponent' , 'EnsemblGene' , 'GoComponent' , 'CGD' , 'CGD' , 'E
                    # xpressionAtlas' , 'GoComponent'
                }
            },
            'targets': 
            {
                'properties': 
                {
                    'target_chembl_id': 'TEXT',
                    # EXAMPLES:
                    # 'CHEMBL2095186' , 'CHEMBL2716' , 'CHEMBL2717' , 'CHEMBL2718' , 'CHEMBL2719' , 'CHEMBL2720' , 'CHEM
                    # BL2721' , 'CHEMBL2722' , 'CHEMBL2723' , 'CHEMBL2724'
                }
            },
            'tax_id': 'NUMERIC',
            # EXAMPLES:
            # '9606' , '9606' , '9606' , '10116' , '9606' , '9913' , '9606' , '9606' , '10090' , '10116'
        }
    }
