# Elastic search mapping definition for the Molecule entity
from glados.es.ws2es.es_util import DefaultMappings

# Shards size - can be overridden from the default calculated value here
# shards = 3,
replicas = 1

analysis = DefaultMappings.COMMON_ANALYSIS

mappings = \
    {
        'properties': 
        {
            'accession': 'TEXT',
            # EXAMPLES:
            # 'O09028' , 'P02708' , 'P04637' , 'P04757' , 'P05106' , 'P05556' , 'P06493' , 'P06756' , 'P07510' , 'P08482
            # '
            'component_id': 'NUMERIC',
            # EXAMPLES:
            # '1' , '2' , '3' , '4' , '5' , '6' , '7' , '8' , '9' , '10'
            'component_type': 'TEXT',
            # EXAMPLES:
            # 'PROTEIN' , 'PROTEIN' , 'PROTEIN' , 'PROTEIN' , 'PROTEIN' , 'PROTEIN' , 'PROTEIN' , 'PROTEIN' , 'PROTEIN' 
            # , 'PROTEIN'
            'description': 'TEXT',
            # EXAMPLES:
            # 'Gamma-aminobutyric acid receptor subunit pi' , 'Acetylcholine receptor subunit alpha' , 'Cellular tumor a
            # ntigen p53' , 'Neuronal acetylcholine receptor subunit alpha-3' , 'Integrin beta-3' , 'Integrin beta-1' , 
            # 'Cyclin-dependent kinase 1' , 'Integrin alpha-V' , 'Acetylcholine receptor subunit gamma' , 'Muscarinic ac
            # etylcholine receptor M1'
            'go_slims': 
            {
                'properties': 
                {
                    'go_id': 'TEXT',
                    # EXAMPLES:
                    # 'GO:0003674' , 'GO:0003674' , 'GO:0002376' , 'GO:0003674' , 'GO:0000902' , 'GO:0000902' , 'GO:0000
                    # 166' , 'GO:0000902' , 'GO:0003674' , 'GO:0003674'
                }
            },
            'organism': 'TEXT',
            # EXAMPLES:
            # 'Rattus norvegicus' , 'Homo sapiens' , 'Homo sapiens' , 'Rattus norvegicus' , 'Homo sapiens' , 'Homo sapie
            # ns' , 'Homo sapiens' , 'Homo sapiens' , 'Homo sapiens' , 'Rattus norvegicus'
            'protein_classifications': 
            {
                'properties': 
                {
                    'protein_classification_id': 'NUMERIC',
                    # EXAMPLES:
                    # '1173' , '422' , '12' , '422' , '11' , '11' , '323' , '11' , '424' , '559'
                }
            },
            'sequence': 'TEXT',
            # EXAMPLES:
            # 'MSYSLYLAFVCLNLLAQRMCIQGNQFNVEVSRSDKLSLPGFENLTAGYNKFLRPNFGGDPVRIALTLDIASISSISESNMDYTATIYLRQRWTDPRLVFEGNKSF
            # TLDARLVEFLWVPDTYIVESKKSFLHEVTVGNRLIRLFSNGTVLYALRITTTVTCNMDLSKYPMDTQTCKLQLESWGYDGNDVEFSWLRGNDSVRGLENLRLAQYT
            # IQQYFTLVTVSQQETGNYTRLVLQFELRRNVLYFILETYVPSTFLVVLSWVSFWISLESVPARTCIGVTTVLSMTTLMIGSRTSLPNTNCFIKAIDVYLGICFSFV
            # FGALLEYAVAHYSSLQQMAVKDRGPAKDSEEVNITNIINSSISSFKRKISFASIEISGDNVNYSDLTMKASDKFKFVFREKIGRIIDYFTIQNPSNVDRYSKLLFP
            # LIFMLANVFYWAYYMYF' , 'MEPWPLLLLFSLCSAGLVLGSEHETRLVAKLFKDYSSVVRPVEDHRQVVEVTVGLQLIQLINVDEVNQIVTTNVRLKQGDMVDL
            # PRPSCVTLGVPLFSHLQNEQWVDYNLKWNPDDYGGVKKIHIPSEKIWRPDLVLYNNADGDFAIVKFTKVLLQYTGHITWTPPAIFKSYCEIIVTHFPFDEQNCSMK
            # LGTWTYDGSVVAINPESDQPDLSNFMESGEWVIKESRGWKHSVTYSCCPDTPYLDITYHFVMQRLPLYFIVNVIIPCLLFSFLTGLVFYLPTDSGEKMTLSISVLL
            # SLTVFLLVIVELIPSTSSAVPLIGKYMLFTMVFVIASIIITVIVINTHHRSPSTHVMPNWVRKVFIDTIPNIMFFSTMKRPSREKQDKKIFTEDIDISDISGKPGP
            # PPMGFHSPLIKHPEVKSAIEGIKYIAETMKSDQESNNAAAEWKYVAMVMDHILLGVFMLVCIIGTLAVFAGRLIELNQQG' , 'MEEPQSDPSVEPPLSQETFSD
            # LWKLLPENNVLSPLPSQAMDDLMLSPDDIEQWFTEDPGPDEAPRMPEAAPPVAPAPAAPTPAAPAPAPSWPLSSSVPSQKTYQGSYGFRLGFLHSGTAKSVTCTYS
            # PALNKMFCQLAKTCPVQLWVDSTPPPGTRVRAMAIYKQSQHMTEVVRRCPHHERCSDSDGLAPPQHLIRVEGNLRVEYLDDRNTFRHSVVVPYEPPEVGSDCTTIH
            # YNYMCNSSCMGGMNRRPILTIITLEDSSGNLLGRNSFEVRVCACPGRDRRTEEENLRKKGEPHHELPPGSTKRALPNNTSSSPQPKKKPLDGEYFTLQIRGRERFE
            # MFRELNEALELKDAQAGKEPGGSRAHSSHLKSKKGQSTSRHKKLMFKTEGPDSD' , 'MGVVLLPPPLSMLMLVLMLLPAASASEAEHRLFQYLFEDYNEIIRPV
            # ANVSHPVIIQFEVSMSQLVKVDEVNQIMETNLWLKQIWNDYKLKWKPSDYQGVEFMRVPAEKIWKPDIVLYNNADGDFQVDDKTKALLKYTGEVTWIPPAIFKSSC
            # KIDVTYFPFDYQNCTMKFGSWSYDKAKIDLVLIGSSMNLKDYWESGEWAIIKAPGYKHEIKYNCCEEIYQDITYSLYIRRLPLFYTINLIIPCLLISFLTVLVFYL
            # PSDCGEKVTLCISVLLSLTVFLLVITETIPSTSLVIPLIGEYLLFTMIFVTLSIVITVFVLNVHYRTPTTHTMPTWVKAVFLNLLPRVMFMTRPTSGEGDTPKTRT
            # FYGAELSNLNCFSRADSKSCKEGYPCQDGTCGYCHHRRVKISNFSANLTRSSSSESVNAVLSLSALSPEIKEAIQSVKYIAENMKAQNVAKEIQDDWKYVAMVIDR
            # IFLWVFILVCILGTAGLFLQPLMARDDT' , 'MRARPRPRPLWATVLALGALAGVGVGGPNICTTRGVSSCQQCLAVSPMCAWCSDEALPLGSPRCDLKENLLKD
            # NCAPESIEFPVSEARVLEDRPLSDKGSGDSSQVTQVSPQRIALRLRPDDSKNFSIQVRQVEDYPVDIYYLMDLSYSMKDDLWSIQNLGTKLATQMRKLTSNLRIGF
            # GAFVDKPVSPYMYISPPEALENPCYDMKTTCLPMFGYKHVLTLTDQVTRFNEEVKKQSVSRNRDAPEGGFDAIMQATVCDEKIGWRNDASHLLVFTTDAKTHIALD
            # GRLAGIVQPNDGQCHVGSDNHYSASTTMDYPSLGLMTEKLSQKNINLIFAVTENVVNLYQNYSELIPGTTVGVLSMDSSNVLQLIVDAYGKIRSKVELEVRDLPEE
            # LSLSFNATCLNNEVIPGLKSCMGLKIGDTVSFSIEAKVRGCPQEKEKSFTIKPVGFKDSLIVQVTFDCDCACQAQAEPNSHRCNNGNGTFECGVCRCGPGWLGSQC
            # ECSEEDYRPSQQDECSPREGQPVCSQRGECLCGQCVCHSSDFGKITGKYCECDDFSCVRYKGEMCSGHGQCSCGDCLCDSDWTGYYCNCTTRTDTCMSSNGLLCSG
            # RGKCECGSCVCIQPGSYGDTCEKCPTCPDACTFKKECVECKKFDRGALHDENTCNRYCRDEIESVKELKDTGKDAVNCTYKNEDDCVVRFQYYEDSSGKSILYVVE
            # EPECPKGPDILVVLLSVMGAILLIGLAALLIWKLLITIHDRKEFAKFEEERARAKWDTANNPLYKEATSTFTNITYRGT' , 'MNLQPIFWIGLISSVCCVFAQT
            # DENRCLKANAKSCGECIQAGPNCGWCTNSTFLQEGMPTSARCDDLEALKKKGCPPDDIENPRGSKDIKKNKNVTNRSKGTAEKLKPEDITQIQPQQLVLRLRSGEP
            # QTFTLKFKRAEDYPIDLYYLMDLSYSMKDDLENVKSLGTDLMNEMRRITSDFRIGFGSFVEKTVMPYISTTPAKLRNPCTSEQNCTSPFSYKNVLSLTNKGEVFNE
            # LVGKQRISGNLDSPEGGFDAIMQVAVCGSLIGWRNVTRLLVFSTDAGFHFAGDGKLGGIVLPNDGQCHLENNMYTMSHYYDYPSIAHLVQKLSENNIQTIFAVTEE
            # FQPVYKELKNLIPKSAVGTLSANSSNVIQLIIDAYNSLSSEVILENGKLSEGVTISYKSYCKNGVNGTGENGRKCSNISIGDEVQFEISITSNKCPKKDSDSFKIR
            # PLGFTEEVEVILQYICECECQSEGIPESPKCHEGNGTFECGACRCNEGRVGRHCECSTDEVNSEDMDAYCRKENSSEICSNNGECVCGQCVCRKRDNTNEIYSGKF
            # CECDNFNCDRSNGLICGGNGVCKCRVCECNPNYTGSACDCSLDTSTCEASNGQICNGRGICECGVCKCTDPKFQGQTCEMCQTCLGVCAEHKECVQCRAFNKGEKK
            # DTCTQECSYFNITKVESRDKLPQPVQPDPVSHCKEKDVDDCWFYFTYSVNGNNEVMVHVVENPECPTGPDIIPIVAGVVAGIVLIGLALLLIWKLLMIIHDRREFA
            # KFEKEKMNAKWDTGENPIYKSAVTTVVNPKYEGK' , 'MEDYTKIEKIGEGTYGVVYKGRHKTTGQVVAMKKIRLESEEEGVPSTAIREISLLKELRHPNIVSLQ
            # DVLMQDSRLYLIFEFLSMDLKKYLDSIPPGQYMDSSLVKSYLYQILQGIVFCHSRRVLHRDLKPQNLLIDDKGTIKLADFGLARAFGIPIRVYTHEVVTLWYRSPE
            # VLLGSARYSTPVDIWSIGTIFAELATKKPLFHGDSEIDQLFRIFRALGTPNNEVWPEVESLQDYKNTFPKWKPGSLASHVKNLDENGLDLLSKMLIYDPAKRISGK
            # MALNHPYFNDLDNQIKKM' , 'MAFPPRRRLRLGPRGLPLLLSGLLLPLCRAFNLDVDSPAEYSGPEGSYFGFAVDFFVPSASSRMFLLVGAPKANTTQPGIVEG
            # GQVLKCDWSSTRRCQPIEFDATGNRDYAKDDPLEFKSHQWFGASVRSKQDKILACAPLYHWRTEMKQEREPVGTCFLQDGTKTVEYAPCRSQDIDADGQGFCQGGF
            # SIDFTKADRVLLGGPGSFYWQGQLISDQVAEIVSKYDPNVYSIKYNNQLATRTAQAIFDDSYLGYSVAVGDFNGDGIDDFVSGVPRAARTLGMVYIYDGKNMSSLY
            # NFTGEQMAAYFGFSVAATDINGDDYADVFIGAPLFMDRGSDGKLQEVGQVSVSLQRASGDFQTTKLNGFEVFARFGSAIAPLGDLDQDGFNDIAIAAPYGGEDKKG
            # IVYIFNGRSTGLNAVPSQILEGQWAARSMPPSFGYSMKGATDIDKNGYPDLIVGAFGVDRAILYRARPVITVNAGLEVYPSILNQDNKTCSLPGTALKVSCFNVRF
            # CLKADGKGVLPRKLNFQVELLLDKLKQKGAIRRALFLYSRSPSHSKNMTISRGGLMQCEELIAYLRDESEFRDKLTPITIFMEYRLDYRTAADTTGLQPILNQFTP
            # ANISRQAHILLDCGEDNVCKPKLEVSVDSDQKKIYIGDDNPLTLIVKAQNQGEGAYEAELIVSIPLQADFIGVVRNNEALARLSCAFKTENQTRQVVCDLGNPMKA
            # GTQLLAGLRFSVHQQSEMDTSVKFDLQIQSSNLFDKVSPVVSHKVDLAVLAAVEIRGVSSPDHVFLPIPNWEHKENPETEEDVGPVVQHIYELRNNGPSSFSKAML
            # HLQWPYKYNNNTLLYILHYDIDGPMNCTSDMEINPLRIKISSLQTTEKNDTVAGQGERDHLITKRDLALSEGDIHTLGCGVAQCLKIVCQVGRLDRGKSAILYVKS
            # LLWTETFMNKENQNHSYSLKSSASFNVIEFPYKNLPIEDITNSTLVTTNVTWGIQPAPMPVPVWVIILAVLAGLLLLAVLVFVMYRMGFFKRVRPPQEEQEREQLQ
            # PHENGEGNSET' , 'MHGGQGPLLLLLLLAVCLGAQGRNQEERLLADLMQNYDPNLRPAERDSDVVNVSLKLTLTNLISLNEREEALTTNVWIEMQWCDYRLRWD
            # PRDYEGLWVLRVPSTMVWRPDIVLENNVDGVFEVALYCNVLVSPDGCIYWLPPAIFRSACSISVTYFPFDWQNCSLIFQSQTYSTNEIDLQLSQEDGQTIEWIFID
            # PEAFTENGEWAIQHRPAKMLLDPAAPAQEAGHQKVVFYLLIQRKPLFYVINIIAPCVLISSVAILIHFLPAKAGGQKCTVAINVLLAQTVFLFLVAKKVPETSQAV
            # PLISKYLTFLLVVTILIVVNAVVVLNVSLRSPHTHSMARGVRKVFLRLLPQLLRMHVRPLAPAAVQDTQSRLQNGSSGWSITTGEEVALCLPRSELLFQQWQRQGL
            # VAAALEKLEKGPELGLSQFCGSLKQAAPAIQACVEACNLIACARHQQSHFDNGNEEWFLVGRVLDRVCFLAMLSLFICGTAGIFLMAHYNRVPALPFPGDPRPYLP
            # SPD' , 'MNTSVPPAVSPNITVLAPGKGPWQVAFIGITTGLLSLATVTGNLLVLISFKVNTELKTVNNYFLLSLACADLIIGTFSMNLYTTYLLMGHWALGTLAC
            # DLWLALDYVASNASVMNLLLISFDRYFSVTRPLSYRAKRTPRRAALMIGLAWLVSFVLWAPAILFWQYLVGERTVLAGQCYIQFLSQPIITFGTAMAAFYLPVTVM
            # CTLYWRIYRETENRARELAALQGSETPGKGGGSSSSSERSQPGAEGSPESPPGRCCRCCRAPRLLQAYSWKEEEEEDEGSMESLTSSEGEEPGSEVVIKMPMVDSE
            # AQAPTKQPPKSSPNTVKRPTKKGRDRGGKGQKPRGKEQLAKRKTFSLVKEKKAARTLSAILLAFILTWTPYNIMVLVSTFCKDCVPETLWELGYWLCYVNSTVNPM
            # CYALCNKAFRDTFRLLLLCRWDKRRWRKIPKRPGSVHRTPSRQC'
            'target_component_synonyms': 
            {
                'properties': 
                {
                    'component_synonym': 'TEXT',
                    # EXAMPLES:
                    # 'GABA(A) receptor subunit pi' , 'Acetylcholine receptor subunit alpha' , 'Antigen NY-CO-13' , 'Acr
                    # a3' , 'CD_antigen=CD61' , 'CD_antigen=CD29' , '2.7.11.22' , 'CD_antigen=CD51' , 'Acetylcholine rec
                    # eptor subunit gamma' , 'Chrm1'
                    'syn_type': 'TEXT',
                    # EXAMPLES:
                    # 'UNIPROT' , 'UNIPROT' , 'UNIPROT' , 'GENE_SYMBOL_OTHER' , 'UNIPROT' , 'UNIPROT' , 'EC_NUMBER' , 'U
                    # NIPROT' , 'UNIPROT' , 'GENE_SYMBOL'
                }
            },
            'target_component_xrefs': 
            {
                'properties': 
                {
                    'xref_id': 'TEXT',
                    # EXAMPLES:
                    # 'GO:0005886' , 'CHRNA1' , 'TP53' , 'GO:0005886' , 'ITGB3' , 'ENSG00000150093' , 'ENSG00000170312' 
                    # , 'ENSG00000138448' , 'CHRNG' , 'GO:0005886'
                    'xref_name': 'TEXT',
                    # EXAMPLES:
                    # 'plasma membrane' , 'Myasthenic syndrome, congenital, fast channel; Myasthenic syndrome, slow-chan
                    # nel congenital' , 'Li-Fraumeni syndrome; Choroid plexus papilloma; Ependymoma, intracranial; Osteo
                    # genic sarcoma; Breast cancer, familial; Hepatoblastoma; Non-Hodgkin lymphoma; Adrenocortical carci
                    # noma; Colorectal cancer' , 'plasma membrane' , 'Glanzmann thrombasthenia' , 'ruffle' , 'cyclin-dep
                    # endent protein kinase holoenzyme complex' , 'cytosol' , 'Multiple pterygium syndrome; Escobar synd
                    # rome' , 'plasma membrane'
                    'xref_src_db': 'TEXT',
                    # EXAMPLES:
                    # 'GoComponent' , 'CGD' , 'CGD' , 'GoComponent' , 'CGD' , 'EnsemblGene' , 'EnsemblGene' , 'EnsemblGe
                    # ne' , 'CGD' , 'GoComponent'
                }
            },
            'targets': 
            {
                'properties': 
                {
                    'target_chembl_id': 'TEXT',
                    # EXAMPLES:
                    # 'CHEMBL1907607' , 'CHEMBL1907588' , 'CHEMBL4096' , 'CHEMBL1907593' , 'CHEMBL1907598' , 'CHEMBL1907
                    # 599' , 'CHEMBL308' , 'CHEMBL1907598' , 'CHEMBL1907588' , 'CHEMBL1907609'
                }
            },
            'tax_id': 'NUMERIC',
            # EXAMPLES:
            # '10116' , '9606' , '9606' , '10116' , '9606' , '9606' , '9606' , '9606' , '9606' , '10116'
        }
    }
