# Elastic search mapping definition for the Molecule entity
from glados.es.ws2es.es_util import DefaultMappings

# Shards size - can be overridden from the default calculated value here
# shards = 3,
replicas = 1

analysis = DefaultMappings.COMMON_ANALYSIS

mappings = \
    {
        'properties': 
        {
            'accession': 'TEXT',
            # EXAMPLES:
            # 'O70276' , 'Q9UJU2' , 'Q9C5U1' , 'O70546' , 'O75356' , 'Q80T43' , 'P04179' , 'Q16773' , 'Q10981' , 'P29411
            # '
            'component_id': 'NUMERIC',
            # EXAMPLES:
            # '18645' , '8494' , '4690' , '18648' , '18649' , '2097' , '17630' , '2281' , '17631' , '3117'
            'component_type': 'TEXT',
            # EXAMPLES:
            # 'PROTEIN' , 'PROTEIN' , 'PROTEIN' , 'PROTEIN' , 'PROTEIN' , 'PROTEIN' , 'PROTEIN' , 'PROTEIN' , 'PROTEIN' 
            # , 'PROTEIN'
            'description': 'TEXT',
            # EXAMPLES:
            # 'Retinoid isomerohydrolase' , 'Lymphoid enhancer-binding factor 1' , 'Histidine kinase 3' , 'Lysine-specif
            # ic demethylase 6A' , 'Ectonucleoside triphosphate diphosphohydrolase 5' , 'Metabotropic glutamate receptor
            #  2' , 'Superoxide dismutase [Mn], mitochondrial' , 'Kynurenine--oxoglutarate transaminase 1' , 'Galactosid
            # e alpha-(1,2)-fucosyltransferase 2' , 'GTP:AMP phosphotransferase AK3, mitochondrial'
            'go_slims': 
            {
                'properties': 
                {
                    'go_id': 'TEXT',
                    # EXAMPLES:
                    # 'GO:0005575' , 'GO:0000902' , 'GO:0003674' , 'GO:0003677' , 'GO:0005515' , 'GO:0004930' , 'GO:0003
                    # 013' , 'GO:0003824' , 'GO:0005794' , 'GO:0000166'
                }
            },
            'organism': 'TEXT',
            # EXAMPLES:
            # 'Rattus norvegicus' , 'Homo sapiens' , 'Arabidopsis thaliana' , 'Mus musculus' , 'Homo sapiens' , 'Mus mus
            # culus' , 'Homo sapiens' , 'Homo sapiens' , 'Homo sapiens' , 'Rattus norvegicus'
            'protein_classifications': 
            {
                'properties': 
                {
                    'protein_classification_id': 'NUMERIC',
                    # EXAMPLES:
                    # '646' , '601' , '1100' , '10' , '646' , '446' , '10' , '1' , '643' , '643'
                }
            },
            'sequence': 'TEXT',
            # EXAMPLES:
            # 'MSIQIEHPAGGYKKLFETVEELSTPLTAHVTGRIPLWLTGSLLRCGPGLFEVGSEPFYHLFDGQALLHKFDFKEGHVTYYRRFIRTDAYVRAMTEKRIVITEFGT
            # CAFPDPCKNIFSRFFSYFRGVEITDNALVNIYPVGEDYYACTETNFITKINPETLETIKQVDLCNYVSVNGATAHPHIESDGTVYNIGNCFGKNFTVAYNIIKIPP
            # LKADKEDPINKSEVVVQFPCSDRFKPSYVHSFGLTPNYIVFVETPVKINLFKFLSSWSLWGANYMDCFESNESMGVWLHVADKKRRKYFNNKYRTSPFNLFHHINT
            # YEDNGFLIVDLCCWKGFEFVYNYLYLANLRENWEEVKRNAMKAPQPEVRRYVLPLTIDKADTGRNLVTLPHTTATAILCSDETIWLEPEVLFSGPRQAFEFPQINY
            # QKCGGKPYTYAYGLGLNHFVPDKLCKLNVKTKEIWMWQEPDSYPSEPIFVSQPDALEEDDGVVLSVVVSPGAGQKPAYLLVLNAKDLSEIARAEVETNIPVTFHGL
            # FKKP' , 'MPQLSGGGGGGGGDPELCATDEMIPFKDEGDPQKEKIFAEISHPEEEGDLADIKSSLVNESEIIPASNGHEVARQAQTSQEPYHDKAREHPDDGKHP
            # DGGLYNKGPSYSSYSGYIMMPNMNNDPYMSNGSLSPPIPRTSNKVPVVQPSHAVHPLTPLITYSDEHFSPGSHPSHIPSDVNSKQGMSRHPPAPDIPTFYPLSPGG
            # VGQITPPLGWQGQPVYPITGGFRQPYPSSLSVDTSMSRFSHHMIPGPPGPHTTGIPHPAIVTPQVKQEHPHTDSDLMHVKPQHEQRKEQEPKRPHIKKPLNAFMLY
            # MKEMRANVVAECTLKESAAINQILGRRWHALSREEQAKYYELARKERQLHMQLYPGWSARDNYGKKKKRKREKLQESASGTGPRMTAAYI' , 'MSLFHVLGFGV
            # KIGHLFWMLCCWFVSWFVDNGIEDKSGLLVGSVGDLEKTKMTTLKKKNKMWFWNKISSSGLKIPSFSYQFLGSVKFNKAWWRKLVVVWVVFWVLVSIWTFWYFSSQ
            # AMEKRKETLASMCDERARMLQDQFNVSMNHVQAMSILISTFHHGKIPSAIDQRTFSEYTDRTSFERPLTSGVAYAMRVLHSEREEFERQQGWTIRKMYSLEQNPVH
            # KDDYDLEALEPSPVQEEYAPVIFAQDTVSHVVSLDMLSGKEDRENVLRARSSGKGVLTAPFPLIKTNRLGVILTFAVYKRDLPSNATPKERIEATNGYLGGVFDIE
            # SLVENLLQQLASKQTILVNVYDITNHSQPISMYGTNVSADGLERVSPLIFGDPLRKHEMRCRFKQKPPWPVLSMVTSFGILVIALLVAHIIHATVSRIHKVEEDCD
            # KMKQLKKKAEAADVAKSQFLATVSHEIRTPMNGVLGMLHMLMDTELDVTQQDYVRTAQASGKALVSLINEVLDQAKIESGKLELEEVRFDLRGILDDVLSLFSSKS
            # QQKGVELAVYISDRVPDMLIGDPGRFRQILTNLMGNSIKFTEKGHIFVTVHLVDELFESIDGETASSPESTLSGLPVADRQRSWENFKAFSSNGHRSFEPSPPDIN
            # LIVSVEDTGVGIPVEAQSRIFTPFMQVGPSISRTHGGTGIGLSISKCLVGLMKGEIGFSSTPKVGSTFTFTAVFSNGMQPAERKNDNNQPIFSEFRGMKAVVVDHR
            # PARAKVSWYHFQRLGIRVEVVPRVEQALHYLKIGTTTVNMILIEQEIWNREADDFIKKLQKDPLFLSPKLILLANSVESSISEALCTGIDPPIVIVKPLRASMLAA
            # TLQRGLGIGIREPPQHKGPPALILRNLLLGRKILIVDDNNVNLRVAAGALKKYGADVVCAESGIKAISLLKPPHEFDACFMDIQMPEMDGFEATRRIRDMEEEMNK
            # RIKNGEALIVENGNKTSWHLPVLAMTADVIQATHEECLKCGMDGYVSKPFEAEQLYREVSRFFNSPSDTES' , 'MKSCGVSLATAAAAAAAAAFGDEEKKMAAG
            # KASGESEEASPSLTAEEREALGGLDSRLFGFVRFHEDGARMKALLGKAVRCYESLILKAEGKVESDFFCQLGHFNLLLEDYPKALSAYQRYYSLQSDYWKNAAFLY
            # GLGLVYFHYNAFQWAIKAFQEVLYVDPSFCRAKEIHLRLGLMFKVNTDYESSLKHFQLALVDCNPCTLSNAEIQFHIAHLYETQRKYHSAKEAYEQLLQTENLSAQ
            # VKATILQQLGWMHHTVDLLGDKATKESYAIQYLQKSLEADPNSGQSWYFLGRCYSSIGKVQDAFISYRQSIDKSEASADTWCSIGVLYQQQNQPMDALQAYICAVQ
            # LDHGHAAAWMDLGTLYESCNQPQDAIKCYLNATRSKNCSNTSGLAARIKYLQAQLCNLPQGSLQNKTKLLPSIEEAWSLPIPAELTSRQGAMNTAQQNTSDNWSGG
            # NAPPPVEQQTHSWCLTPQKLQHLEQLRANRNNLNPAQKLMLEQLESQFVLMQQHQMRQTGVAQVRPTGILNGPTVDSSLPTNSVSGQQPQLPLTRMPSVSQPGVHT
            # ACPRQTLANGPFSAGHVPCSTSRTLGSTDTVLIGNNHVTGSGSNGNVPYLQRNAPTLPHNRTNLTSSTEEPWKNQLSNSTQGLHKGPSSHLAGPNGERPLSSTGPS
            # QHLQAAGSGIQNQNGHPTLPSNSVTQGAALNHLSSHTATSGGQQGITLTKESKPSGNTLTVPETSRQTGETPNSTASVEGLPNHVHQVMADAVCSPSHGDSKSPGL
            # LSSDNPQLSALLMGKANNNVGPGTCDKVNNIHPTVHTKTDNSVASSPSSAISTATPSPKSTEQTTTNSVTSLNSPHSGLHTINGEGMEESQSPIKTDLLLVSHRPS
            # PQIIPSMSVSIYPSSAEVLKACRNLGKNGLSNSSILLDKCPPPRPPSSPYPPLPKDKLNPPTPSIYLENKRDAFFPPLHQFCTNPNNPVTVIRGLAGALKLDLGLF
            # STKTLVEANNEHMVEVRTQLLQPADENWDPTGTKKIWHCESNRSHTTIAKYAQYQASSFQESLREENEKRSHHKDHSDSESTSSDNSGKRRKGPFKTIKFGTNIDL
            # SDDKKWKLQLHELTKLPAFVRVVSAGNLLSHVGHTILGMNTVQLYMKVPGSRTPGHQENNNFCSVNINIGPGDCEWFVVPEGYWGVLNDFCEKNNLNFLMGSWWPN
            # LEDLYEANVPVYRFIQRPGDLVWINAGTVHWVQAIGWCNNIAWNVGPLTACQYKLAVERYEWNKLQNVKSIVPMVHLSWNMARNIKVSDPKLFEMIKYCLLRTLKQ
            # CQTLREALIAAGKEIIWHGRTKEEPAHYCSICEVEVFDLLFVTNESNSRKTYIVHCQDCARKTSGNLENFVVLEQYKMEDLMQVYDQFTLAPPLPSASS' , 'MA
            # TSWGTVFFMLVVSCVCSAVSHRNQQTWFEGIFLSSMCPINVSASTLYGIMFDAGSTGTRIHVYTFVQKMPGQLPILEGEVFDSVKPGLSAFVDQPKQGAETVQGLL
            # EVAKDSIPRSHWKKTPVVLKATAGLRLLPEHKAKALLFEVKEIFRKSPFLVPKGSVSIMDGSDEGILAWVTVNFLTGQLHGHRQETVGTLDLGGASTQITFLPQFE
            # KTLEQTPRGYLTSFEMFNSTYKLYTHSYLGFGLKAARLATLGALETEGTDGHTFRSACLPRWLEAEWIFGGVKYQYGGNQEGEVGFEPCYAEVLRVVRGKLHQPEE
            # VQRGSFYAFSYYYDRAVDTDMIDYEKGGILKVEDFERKAREVCDNLENFTSGSPFLCMDLSYITALLKDGFGFADSTVLQLTKKVNNIETGWALGATFHLLQSLGI
            # SH' , 'DAPTAITGVIGGSYSDVSIQVANLLRLFQIPQISYASTSAKLSDKSRYDYFARTVPPDFFQAKAMAEILRFFNWTYVSTVASEGDYGETGIEAFELEAR
            # ARNICVATSEKVGRAMSRAAFEGVVRALLQKPSARVAVLFTRSEDARELLAATQRLNASFTWVASDGWGALESVVA' , 'MLSRAVCGTSRQLAPVLGYLGSRQK
            # HSLPDLPYDYGALEPHINAQIMQLHHSKHHAAYVNNLNVTEEKYQEALAKGDVTAQIALQPALKFNGGGHINHSIFWTNLSPNGGGEPKGELLEAIKRDFGSFDKF
            # KEKLTAASVGVQGSGWGWLGFNKERGHLQIAACPNQDPLQGTTGLIPLLGIDVWEHAYYLQYKNVRPDYLKAIWNVINWENVTERYMACKK' , 'MAKQLQARRL
            # DGIDYNPWVEFVKLASEHDVVNLGQGFPDFPPPDFAVEAFQHAVSGDFMLNQYTKTFGYPPLTKILASFFGELLGQEIDPLRNVLVTVGGYGALFTAFQALVDEGD
            # EVIIIEPFFDCYEPMTMMAGGRPVFVSLKPGPIQNGELGSSSNWQLDPMELAGKFTSRTKALVLNTPNNPLGKVFSREELELVASLCQQHDVVCITDEVYQWMVYD
            # GHQHISIASLPGMWERTLTIGSAGKTFSATGWKVGWVLGPDHIMKHLRTVHQNSVFHCPTQSQAAVAESFEREQLLFRQPSSYFVQFPQAMQRCRDHMIRSLQSVG
            # LKPIIPQGSYFLITDISDFKRKMPDLPGAVDEPYDRRFVKWMIKNKGLVAIPVSIFYSVPHQKHFDHYIRFCFVKDEATLQAMDEKLRKWKVEL' , 'MLVVQMP
            # FSFPMAHFILFVFTVSTIFHVQQRLAKIQAMWELPVQIPVLASTSKALGPSQLRGMWTINAIGRLGNQMGEYATLYALAKMNGRPAFIPAQMHSTLAPIFRITLPV
            # LHSATASRIPWQNYHLNDWMEEEYRHIPGEYVRFTGYPCSWTFYHHLRQEILQEFTLHDHVREEAQKFLRGLQVNGSRPGTFVGVHVRRGDYVHVMPKVWKGVVAD
            # RRYLQQALDWFRARYSSLIFVVTSNGMAWCRENIDTSHGDVVFAGDGIEGSPAKDFALLTQCNHTIMTIGTFGIWAAYLTGGDTIYLANYTLPDSPFLKIFKPEAA
            # FLPEWTGIAADLSPLLKH' , 'MGASGRLLRAVIMGAPGSGKGTGSSRITKHFELKHLSSGDLLRQNMLQGTEIAVLAKSFIDQGKLIPDDDMTRLALHELKNLT
            # QCSWLLDGFPRTLPQAEALDRVYQIDTVINLNVPFEVIKLRLTARWIHPASGRVYNIEFNPPKTVGIDDLTGEPLIQREDDKPETVIKRLKAYEAQTEPVLQYYQK
            # KGVLETFSGTETNKIRPHVYSFLQMKVPETIQKASVTP'
            'target_component_synonyms': 
            {
                'properties': 
                {
                    'component_synonym': 'TEXT',
                    # EXAMPLES:
                    # '3.1.1.64' , 'LEF1' , '2.7.13.3' , '1.14.11.68' , '3.6.1.42' , 'Grm2' , '1.15.1.1' , '2.6.1.64' , 
                    # '2.4.1.344' , '2.7.4.10'
                    'syn_type': 'TEXT',
                    # EXAMPLES:
                    # 'EC_NUMBER' , 'GENE_SYMBOL' , 'EC_NUMBER' , 'EC_NUMBER' , 'EC_NUMBER' , 'GENE_SYMBOL' , 'EC_NUMBER
                    # ' , 'EC_NUMBER' , 'EC_NUMBER' , 'EC_NUMBER'
                }
            },
            'target_component_xrefs': 
            {
                'properties': 
                {
                    'xref_id': 'TEXT',
                    # EXAMPLES:
                    # 'GO:0005634' , 'ENSG00000138795' , 'Q9C5U1' , 'O70546' , 'ENSG00000187097' , 'GO:0016020' , 'ENSG0
                    # 0000112096' , 'ENSG00000171097' , 'ENSG00000176920' , 'GO:0005737'
                    'xref_name': 'TEXT',
                    # EXAMPLES:
                    # 'nucleus' , 'nucleus' , 'nucleus' , 'chromatin' , 'extracellular region' , 'membrane' , 'mitochond
                    # rion' , 'cytoplasm' , 'Golgi apparatus' , 'cytoplasm'
                    'xref_src_db': 'TEXT',
                    # EXAMPLES:
                    # 'GoComponent' , 'EnsemblGene' , 'ExpressionAtlas' , 'ExpressionAtlas' , 'EnsemblGene' , 'GoCompone
                    # nt' , 'EnsemblGene' , 'EnsemblGene' , 'EnsemblGene' , 'GoComponent'
                    'xref_src_url': 'TEXT',
                    # EXAMPLES:
                    # 'http://www.ebi.ac.uk/QuickGO/' , 'http://www.ensembl.org/' , 'http://www.ebi.ac.uk/gxa/' , 'http:
                    # //www.ebi.ac.uk/gxa/' , 'http://www.ensembl.org/' , 'http://www.ebi.ac.uk/QuickGO/' , 'http://www.
                    # ensembl.org/' , 'http://www.ensembl.org/' , 'http://www.ensembl.org/' , 'http://www.ebi.ac.uk/Quic
                    # kGO/'
                    'xref_url': 'TEXT',
                    # EXAMPLES:
                    # 'http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0005634' , 'http://www.ensembl.org/Gene/Summary?g=ENSG00
                    # 000138795' , 'http://www.ebi.ac.uk/gxa/query?geneQuery=Q9C5U1' , 'http://www.ebi.ac.uk/gxa/query?g
                    # eneQuery=O70546' , 'http://www.ensembl.org/Gene/Summary?g=ENSG00000187097' , 'http://www.ebi.ac.uk
                    # /QuickGO/GTerm?id=GO:0016020' , 'http://www.ensembl.org/Gene/Summary?g=ENSG00000112096' , 'http://
                    # www.ensembl.org/Gene/Summary?g=ENSG00000171097' , 'http://www.ensembl.org/Gene/Summary?g=ENSG00000
                    # 176920' , 'http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0005737'
                }
            },
            'targets': 
            {
                'properties': 
                {
                    'target_chembl_id': 'TEXT',
                    # EXAMPLES:
                    # 'CHEMBL4523147' , 'CHEMBL3217392' , 'CHEMBL6125' , 'CHEMBL4523151' , 'CHEMBL4105776' , 'CHEMBL3962
                    # ' , 'CHEMBL4105777' , 'CHEMBL4799' , 'CHEMBL3085617' , 'CHEMBL1075305'
                }
            },
            'tax_id': 'NUMERIC',
            # EXAMPLES:
            # '10116' , '9606' , '3702' , '10090' , '9606' , '10090' , '9606' , '9606' , '9606' , '10116'
        }
    }
